Repository POB-Coconut/Assignment-3, pull requests merged in 2021-08, with the labels that each got.

#14 Feat: 관리자 페이지 스타일링
  public/images/Logo.jpg
  public/images/jaranda-logo.png
  public/index.html
  src/components/AccountButton.jsx
  src/components/Navbar.jsx
  src/components/SearchBox.jsx
  src/pages/Admin.jsx
  src/pages/User.jsx
  src/styles/GlobalStyles.js
  src/styles/icons/SearchIcon.jsx
  src/styles/layouts.js
Labels: Status: Accepted

#19 Feat: useInput hook, validation regex test 구현
  .eslintrc
  .gitignore
  .prettierrc
  src/Routes.js
  src/components/AccountButton.js
  src/components/Graph.js
  src/hooks/useForm.js
  src/hooks/useInput.js
  src/pages/Signup.jsx
  src/utils/regex.js
  src/utils/storage/index.js
Labels: Status: 리뷰 요청

#25 Feat: 로그인/회원가입 페이지 레이아웃 및 스타일
  .eslintrc
  package-lock.json
  package.json
  public/index.html
  src/components/Navbar.js
  src/components/Pagination.js
  src/components/SignIn.js
  src/components/SignUp.js
  src/components/Table.js
  src/components/UserTable.js
  src/components/index.js
  src/pages/Login.js
  src/styles/styles.js
  src/utils/config.js
  src/utils/constants.js
  src/utils/storage/index.js
Labels: Status: Accepted

#38 PR: cardNumber 모달창 구현
  src/components/CardNumber.js
  src/components/SignUp.js
Labels: Status: Accepted, Status: 리뷰 요청

#32 Feat: useForm hook 적용, validation 보완, 로그인 적용 로직 구성 중
  .eslintrc
  src/Routes.js
  src/components/SignIn.js
  src/components/SignInForm.js
  src/components/SignUp.js
  src/hooks/useForm.js
  src/pages/Signup.js
  src/styles/InputWrapper.js
  src/utils/regex.js
Labels: Status: 리뷰 요청, Status: 추가 기능 구현중

#42 Feat: validation login/signup 분리, login 권한 전달 및 페이지 전환 구현 중
  .eslintrc
  src/components/Address.js
  src/components/SignIn.js
  src/components/SignUp.js
  src/pages/User.js
  src/utils/regex.js
Labels: Status: 리뷰 요청

#43 Feat : User & Admin 페이지 스타일링 / Chart 디자인
  package-lock.json
  package.json
  public/images/jaranda-logo.png
  public/images/user-img.png
  src/components/AccountButton.js
  src/components/Chart.js
  src/components/Graph.js
  src/components/Navbar.js
  src/components/SearchBox.js
  src/components/UserTable.js
  src/components/chart/BarChart.js
  src/components/chart/DoughnutChart.js
  src/components/chart/LineChart.js
  src/components/index.js
  src/index.js
  src/pages/Admin.js
  src/pages/User.js
  src/styles/icons/SearchIcon.js
  src/styles/layouts.js
  src/styles/styles.js
  src/utils/config.js
  yarn.lock
Labels: Status: 리뷰 요청

#56 [Feature/chart] Chart data 적용 완료
  .eslintrc
  src/components/Chart.js
  src/components/chart/BarChart.js
  src/components/chart/DoughnutChart.js
  src/components/chart/LineChart.js
  src/pages/Admin.js
Labels: Status: Accepted

#70 [Feature/user style fix] User style 수정
  public/images/parent.png
  public/images/studentLogo.png
  public/images/teacher.png
  public/images/teacherLogo.png
  src/components/UserCard.js
  src/pages/User.js
Labels: Status: 리뷰 요청
